#!/usr/bin/env sh
echo === Source ====================================================================
cloc src --fullpath --not-match-d=/static/

echo
echo === Tests =====================================================================
cloc tests

echo
echo === Nix Automation ============================================================
cloc nix/ *.nix
