"""Add propositions.visibility

Revision ID: 334e65ad89c0
Revises: 58d61f975f05
Create Date: 2020-05-04 22:14:13.106729

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '334e65ad89c0'
down_revision = '58d61f975f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE propositionvisibility AS ENUM ('PUBLIC', 'UNLISTED', 'HIDDEN')")
    op.add_column(
        'propositions',
        sa.Column(
            'visibility',
            sa.Enum('PUBLIC', 'UNLISTED', 'HIDDEN', name='propositionvisibility'),
            server_default='PUBLIC',
            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propositions', 'visibility')
    op.execute("DROP TYPE propositionvisibility")
    # ### end Alembic commands ###
