"""registration_start_days and registration_end_days for VotingPhase and VotingPhaseType

Revision ID: 4c6df443cb98
Revises: ec225b9c33e3
Create Date: 2021-07-13 22:59:22.452903

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4c6df443cb98'
down_revision = 'ec225b9c33e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'voting_phase_types',
        sa.Column(
            'registration_start_days',
            sa.Integer(),
            nullable=True,
            comment='voter registration start in days relative to target date'
        )
    )
    op.add_column(
        'voting_phase_types',
        sa.Column(
            'registration_end_days',
            sa.Integer(),
            nullable=True,
            comment='voter registration end in days relative to target date'
        )
    )
    op.add_column(
        'votingphases',
        sa.Column(
            'registration_start_days',
            sa.Integer(),
            nullable=True,
            comment='voter registration start in days relative to target date'
        )
    )
    op.add_column(
        'votingphases',
        sa.Column(
            'registration_end_days',
            sa.Integer(),
            nullable=True,
            comment='voter registration end in days relative to target date'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votingphases', 'registration_end_days')
    op.drop_column('votingphases', 'registration_start_days')
    op.drop_column('voting_phase_types', 'registration_end_days')
    op.drop_column('voting_phase_types', 'registration_start_days')
    # ### end Alembic commands ###
