"""Add propositionnotes

Revision ID: 911c994268aa
Revises: 2ef4af95efe9
Create Date: 2020-09-01 23:33:46.252308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911c994268aa'
down_revision = '24e8f6789a15'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('propositionnotes',
    sa.Column('proposition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vote', sa.Enum('UNSURE', 'ACCEPT', 'DECLINE', 'ABSTENTION', name='votebyuser'), nullable=True),
    sa.ForeignKeyConstraint(['proposition_id'], ['propositions.id'], name=op.f('fk_propositionnotes_proposition_id_propositions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_propositionnotes_user_id_users')),
    sa.PrimaryKeyConstraint('proposition_id', 'user_id', name=op.f('pk_propositionnotes'))
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propositionnotes')
    # ### end Alembic commands ###
