"""Add Department.exporter_settings

Revision ID: a4817cb50cc4
Revises: 334e65ad89c0
Create Date: 2020-05-05 22:39:47.603012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4817cb50cc4'
down_revision = '334e65ad89c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'departments',
        sa.Column('exporter_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'exporter_settings')
    # ### end Alembic commands ###
