"""VotingPhase.voting_module_data

Revision ID: a6b28eb78241
Revises: d3e7679ab5e3
Create Date: 2020-10-16 19:12:52.879706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6b28eb78241'
down_revision = 'd3e7679ab5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votingphases', sa.Column('voting_module_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votingphases', 'voting_module_data')
    # ### end Alembic commands ###
