"""VVVote voting

Revision ID: d3e7679ab5e3
Revises: 6d782ad96592
Create Date: 2020-10-13 22:16:39.210885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3e7679ab5e3'
down_revision = '6d782ad96592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting_module')
    op.add_column('departments', sa.Column('voting_module_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'voting_module_settings')
    op.create_table('voting_module',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('module_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_voting_module'),
    sa.UniqueConstraint('name', name='uq_voting_module_name')
    )
    # ### end Alembic commands ###
