"""VotingPhase.voting_module_data

Revision ID: e2ce064655e8
Revises: a6b28eb78241
Create Date: 2020-10-16 20:07:08.939257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ce064655e8'
down_revision = 'a6b28eb78241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
