"""voting_days for VotingPhase and VotingPhaseType

Revision ID: ec225b9c33e3
Revises: 50a310f352b0
Create Date: 2021-07-10 16:11:51.416233

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ec225b9c33e3'
down_revision = '50a310f352b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'voting_phase_types',
        sa.Column('voting_days', sa.Integer(), nullable=True, comment='voting duration in days; ends at target date')
    )
    op.add_column(
        'votingphases',
        sa.Column('voting_days', sa.Integer(), nullable=True, comment='voting duration in days; ends at target date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votingphases', 'voting_days')
    op.drop_column('voting_phase_types', 'voting_days')
    # ### end Alembic commands ###
